# Generated by Django 6.0.6 on 2026-06-10 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_time', models.DateTimeField()),
                ('prediction_lock_time', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
                ('team1_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='tournaments.team')),
                ('team2_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='tournaments.team')),
                ('tournament_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournaments')),
            ],
        ),
    ]
