# Generated by Django 6.0.6 on 2026-06-23 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='team2_id',
            new_name='away_team',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='team1_id',
            new_name='home_team',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='match_time',
            new_name='kickoff',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='tournament_id',
            new_name='tournament',
        ),
        migrations.RemoveField(
            model_name='match',
            name='status',
        ),
        migrations.AddField(
            model_name='match',
            name='away_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='home_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
