# Generated by Django 6.0.6 on 2026-06-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
