# Generated by Django 6.0.6 on 2026-06-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_total_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='favascv', max_length=60),
            preserve_default=False,
        ),
    ]
