# Generated by Django 6.0.6 on 2026-06-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_phone_number_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('club_admin', 'Club Admin'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
