# Generated by Django 6.0.6 on 2026-06-23 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_clubinvite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club_member',
            old_name='club_id',
            new_name='club',
        ),
        migrations.RenameField(
            model_name='club_member',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='club_member',
            name='role',
            field=models.CharField(choices=[('club_admin', 'Club Admin'), ('member', 'Member')], max_length=25),
        ),
    ]
